nd: 0day says mips does not have ioremap_cache()
Make NFIT test depend on ACPI which in turns guarantees some base
architecture assumptions.

This resolves:

   drivers/block/nd/test/iomap.c: In function '__wrap_ioremap_cache':
>> drivers/block/nd/test/iomap.c:18:2: error: implicit declaration of
>> function 'ioremap_cache' [-Werror=implicit-function-declaration]
     return ioremap_cache(offset, size);
     ^
>> drivers/block/nd/test/iomap.c:18:2: warning: return makes pointer
>> from integer without a cast
   cc1: some warnings being treated as errors

Reported-by: kbuild test robot <fengguang.wu@intel.com>