- qlcnic: Fix build failure due to undefined reference to   `vxlan_get_rx_port' (bsc#922064 FATE#318609). - Update config files.
suse-commit: f9de3d678265773f48c6a3b56d1d0e8c7c3dd900