x86: fix breakage in UML build
So this breaks the UML build:

/home/mingo/tip/arch/x86/include/asm/special_insns.h: In function ‘pcommit_sfence’:
/home/mingo/tip/arch/x86/include/asm/special_insns.h:218:14: error: expected ‘:’ or ‘)’ before ‘ASM_NOP7’

Signed-off-by: Ross Zwisler <ross.zwisler@linux.intel.com>
Reported-by: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>