0day: implicit declarations of vfree & vmalloc
0day found this while cross-compiling for ia64.

drivers/block/nd/dimm.c: In function 'free_data':
drivers/block/nd/dimm.c:149:3: error: implicit declaration of function 'vfree' [-Werror=implicit-function-declaration]
   vfree(nd_dimm->data);
   ^
drivers/block/nd/dimm.c: In function 'nd_dimm_probe':
drivers/block/nd/dimm.c:173:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]
   nd_dimm->data = vmalloc(cmd_get_config_size);
   ^
drivers/block/nd/dimm_devs.c: In function 'nd_dimm_set_config_data':
drivers/block/nd/dimm_devs.c:234:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]
   cmd = vmalloc(size);
   ^
drivers/block/nd/dimm_devs.c:256:3: error: implicit declaration of function 'vfree' [-Werror=implicit-function-declaration]
   vfree(cmd);
   ^
drivers/block/nd/old_acpi.c: In function 'nd_old_acpi_ctl':
drivers/block/nd/old_acpi.c:196:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]
   buf = vmalloc(buf_len);
   ^
drivers/block/nd/old_acpi.c:310:3: error: implicit declaration of function 'vfree' [-Werror=implicit-function-declaration]
   vfree(buf);

Also, reorder one of the includes in nd/dimm_devs.c so it follows the
longest-to-shortest ordering.

Signed-off-by: Ross Zwisler <ross.zwisler@linux.intel.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>