nd: missing headers in nd-private.h, bus.c, and dimm_devs.c
Note the report below also complained about a non-zero argument to
__builtin_return_address(), also fixed up.

0day says:
   In file included from drivers/block/nd/bus.c:25:0:
   drivers/block/nd/nd-private.h: In function 'to_interleave_set_key':
>> drivers/block/nd/nd-private.h:87:2: error: implicit declaration of function 'readw' [-Werror=implicit-function-declaration]
     u16 dcr_index = readw(&nd_mem->nfit_mem->dcr_index);
     ^
   drivers/block/nd/bus.c: In function 'nd_async_dimm_delete':
   drivers/block/nd/bus.c:142:2: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]
     nfit_handle = readl(&nd_mem->nfit_mem->nfit_handle);
     ^
   drivers/block/nd/bus.c: In function 'revision_show':
   drivers/block/nd/bus.c:383:2: error: implicit declaration of function 'readb' [-Werror=implicit-function-declaration]
     return sprintf(buf, "%d\n", readb(&nfit->revision));
     ^
   drivers/block/nd/bus.c: In function '__nd_ioctl':
   drivers/block/nd/bus.c:636:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]
      buf = vmalloc(buf_len);
      ^
   drivers/block/nd/bus.c:636:7: warning: assignment makes pointer from integer without a cast
      buf = vmalloc(buf_len);
          ^
   drivers/block/nd/bus.c:660:3: error: implicit declaration of function 'vfree' [-Werror=implicit-function-declaration]
      vfree(buf);
      ^
   cc1: some warnings being treated as errors
--
   In file included from drivers/block/nd/dimm_devs.c:18:0:
   drivers/block/nd/nd-private.h: In function 'to_interleave_set_key':
>> drivers/block/nd/nd-private.h:87:2: error: implicit declaration of function 'readw' [-Werror=implicit-function-declaration]
     u16 dcr_index = readw(&nd_mem->nfit_mem->dcr_index);
     ^
   drivers/block/nd/dimm_devs.c: In function '__validate_dimm':
   drivers/block/nd/dimm_devs.c:46:2: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]
     *nfit_handle = readl(&nfit_mem->nfit_handle);
     ^
   In file included from include/linux/printk.h:257:0,
                    from include/linux/kernel.h:13,
                    from include/linux/kernfs.h:10,
                    from include/linux/sysfs.h:15,
                    from include/linux/kobject.h:21,
                    from include/linux/device.h:17,
                    from drivers/block/nd/dimm_devs.c:14:
   drivers/block/nd/dimm_devs.c: In function 'validate_dimm':
   include/linux/dynamic_debug.h:86:3: warning: unsupported argument to '__builtin_return_address'
      __dynamic_dev_dbg(&descriptor, dev, fmt, \
      ^
   include/linux/device.h:1104:2: note: in expansion of macro 'dynamic_dev_dbg'
     dynamic_dev_dbg(dev, format, ##__VA_ARGS__); \
     ^
   drivers/block/nd/dimm_devs.c:56:3: note: in expansion of macro 'dev_dbg'
      dev_dbg(&nd_dimm->dev, "%pf: %s error: %d\n",
      ^
   cc1: some warnings being treated as errors
--
   In file included from drivers/block/nd/region_devs.c:15:0:
   drivers/block/nd/nd-private.h: In function 'to_interleave_set_key':
>> drivers/block/nd/nd-private.h:87:2: error: implicit declaration of function 'readw' [-Werror=implicit-function-declaration]
     u16 dcr_index = readw(&nd_mem->nfit_mem->dcr_index);
     ^
   drivers/block/nd/region_devs.c: In function 'mappingN':
   drivers/block/nd/region_devs.c:342:2: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]
     return sprintf(buf, "%#x,%llu,%llu\n", readl(&nfit_mem->nfit_handle),
     ^
   drivers/block/nd/region_devs.c: In function 'nd_blk_init':
   drivers/block/nd/region_devs.c:480:2: error: implicit declaration of function 'readq' [-Werror=implicit-function-declaration]
     nd_mapping->size = readq(&nd_bdw->nfit_bdw->dimm_capacity);
     ^
   cc1: some warnings being treated as errors
--
   In file included from drivers/block/nd/btt_devs.c:17:0:
   drivers/block/nd/nd-private.h: In function 'to_interleave_set_key':
>> drivers/block/nd/nd-private.h:87:2: error: implicit declaration of function 'readw' [-Werror=implicit-function-declaration]
     u16 dcr_index = readw(&nd_mem->nfit_mem->dcr_index);
     ^
   cc1: some warnings being treated as errors

Reported-by: kbuild test robot <fengguang.wu@intel.com>